# base image: Python 3.11
FROM python:3.11-slim

# install linux package
RUN apt-get update && apt-get install -y curl

# configure working directory
WORKDIR /app

# 의존성 파일 복사
COPY requirements.txt .

# install packages
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 소스 코드 복사
COPY . .

# 컨테이너의 8080 포트를 외부에 노출
EXPOSE 8080

# FastAPI 서버 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]