# 베이스 이미지 설정 (AMD64 전용, Python 3.9-slim 사용)
FROM --platform=linux/amd64 python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    gnupg \
    ca-certificates \
    unzip \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libxss1 \
    libxtst6 \
    libu2f-udev \
    libvulkan1 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 필요한 Python 패키지 설치 + /app/gmarket 디렉토리 생성
COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && mkdir /app/gmarket

# 현재 디렉토리의 모든 파일을 컨테이너의 /app/gmarket에 복사
COPY . /app/gmarket

# Chrome 및 ChromeDriver 다운로드 및 설치 (AMD64 전용)
RUN wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.119/linux64/chrome-linux64.zip -O /tmp/chrome-linux64.zip \
    && unzip /tmp/chrome-linux64.zip -d /opt/chrome \
    && ln -s /opt/chrome/chrome-linux64/chrome /usr/bin/google-chrome

RUN wget https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.119/linux64/chromedriver-linux64.zip -O /tmp/chromedriver-linux64.zip \
    && unzip /tmp/chromedriver-linux64.zip -d /opt/chromedriver \
    && ln -s /opt/chromedriver/chromedriver-linux64/chromedriver /usr/bin/chromedriver

# 환경 변수 설정: chromedriver의 경로를 설정
ENV PATH="/opt/chromedriver:${PATH}"
ENV CHROME_BIN="/usr/bin/google-chrome"
ENV CHROME_DRIVER="/usr/bin/chromedriver"

CMD ["python3", "/app/gmarket/main.py"]